### ISSUE TITLE
Explicar como desenhar outras figuras geométricas no Pyxel

### ISSUE THREAD

**Issue by BrunaNayara** [pyladiesdf/flappy-tutorial#5]
[Aqui](https://github.com/pyladiesdf/flappy-tutorial/blob/master/docs/p3-desenhar.md) já ensina como desenhar algumas básicas, mas sempre podemos melhorar e ensinar um pouco mais. se quiser, pode colocar uns prints também

**Comment by fabiommendes** [comment]
O tutorial cobre o básico, mas talvez seja legal fazer algum follow up ou traduzir o README do pyxel que tem a documentação completa.
